#!/bin/bash

set -e

vbar add-css --class bar --css "font-family: Hack;"
vbar add-css --class bar --css "font-weight: normal;"
vbar add-css --class bar --css "font-size: 20px;"
vbar add-css --class bar --css "text-shadow: none;"
vbar add-css --class bar --css "background-color: #1b202a;"
vbar add-css --class bar --css "border: 10px solid #1b202a;"

vbar add-css --class block --css "padding-top: 5px;"
vbar add-css --class block --css "padding-bottom: 5px;"
vbar add-css --class block --css "padding-left: 10px;"
vbar add-css --class block --css "padding-right: 10px;"
vbar add-css --class block --css "color: #9aa7bd;"
vbar add-css --class block --css "background-color: #323c4d;"

vbar add-css --class menu --css "font-family: Hack;"
vbar add-css --class menu --css "font-weight: normal;"
vbar add-css --class menu --css "font-size: 20px;"
vbar add-css --class menu --css "text-shadow: none;"
vbar add-css --class menu --css "background-color: #323c4d;"
vbar add-css --class menu --css "color: #9aa7bd;"
vbar add-css --class menu --css "border: 10px solid #323c4d;"

vbar add-css --class "menu :hover" --css "background-color: #232936;"
vbar add-css --class "menu :hover" --css "color: #9aa7bd;"

vbar add-css --class power-off-icon --css "font-family: \"Font Awesome\";"
vbar add-css --class power-off-icon --css "background-color: #232936;"

vbar add-css --class title --css "background-color: #1b202a;"

vbar add-css --class battery-icon --css "font-family: \"Font Awesome\";"
vbar add-css --class battery-icon --css "background-color: #232936;"

vbar add-css --class battery --css "margin-right: 10px;"

vbar add-css --class volume-icon --css "font-family: \"Font Awesome\";"
vbar add-css --class volume-icon --css "background-color: #232936;"

vbar add-css --class volume --css "margin-right: 10px;"

vbar add-css --class wireless-icon --css "font-family: \"Font Awesome\";"
vbar add-css --class wireless-icon --css "background-color: #232936;"

vbar add-css --class wireless --css "margin-right: 10px;"

vbar add-css --class date --css "margin-right: 10px;"

vbar add-css --class time --css "margin-right: 0px;"

vbar add-block --left --name power-off-icon --text ""

vbar add-menu --name power-off-icon --text "Log off" --command "bspc quit"
vbar add-menu --name power-off-icon --text "Shut down" --command "systemctl poweroff"

vbar add-block --center --name title --tail-command "xtitle -s"

vbar add-block --right --name volume-icon --command "volume.sh icon" --click-command "amixer -q sset Master toggle && vbar update --name volume && vbar update --name volume-icon"

vbar add-block --right --name volume --command "volume.sh percentage"

vbar add-block --right --name battery-icon --text ''
vbar add-block --right --name battery --tail-command "while true; do acpi | cut -d, -f2 | sed 's/ //'; sleep 5; done"

if command netctl-auto; then
  vbar add-block --right --name wireless-icon --text ""
  vbar add-block --right --name wireless --command "netctl-auto list | grep '* ' | sed 's/* //'" --interval 5
elif command iwgetid; then
  vbar add-block --right --name wireless-icon --text ""
  vbar add-block --right --name wireless --command "iwgetid -r" --interval 5
fi

vbar add-block --right --name date --command "date +%d/%m" --interval 60
vbar add-block --right --name time --command "date +%H:%M" --interval 1
